title: "Footer Navigation"
description: |
  The basic footer navigation that will be used to guide the user through all subpages and categories that will be accessible to the viewer.

  The second, and less visible, of the navigations, this footer provides links to all of the other basic pages within the site itself. This includes the subcategories within the shop, contact information for the company, and other side tasks that visitors may need while accessing the site.

patterns:
  footer:
    title: "Basic Site Footer Navigation"
    width: "65em"
