title: "Store Layout Cards"
description: |
  A selection of example form fields, to be used to build out checkout and other varieties of forms required throughout the website.

patterns:
  stonecategory:
    title: "Material - Stone"
    description: |
      The first of the basic form fields, this is mandatory and thus, requires a valid input before proceeding.
    width: "45em"
  woodcategory:
    title: "Material - Wood"
    description: |
      The second basic form field, these fields are denoted as optional. The information may apply to many, but not all.
    width: "45em"
  glasscategory:
    title: "Material - Glass"
    description: |
      The second basic form field, these fields are denoted as optional. The information may apply to many, but not all.
    width: "45em"
  metalcategory:
    title: "Material - Metal"
    description: |
      The second basic form field, these fields are denoted as optional. The information may apply to many, but not all.
    width: "45em"
  productsgrid:
    title: "Product Grid"
    description: |
      The basic organization of 8 products within the store layout.
    width: "45em"
  layouttitle:
    title: "Variable Title"
    description: |
      A basic titling format free of banners that can be adapted and placed throughout.
    width: "45em"
    fields:
    - name: heading
      type: title
      example: "Example Passage Title"
