title: "Main Image Banners"
description: |
  A selection of main header banner images that will be used throughout the website as the main distinctions between pages.

patterns:
  mainbanner:
    title: "Main Welcome Banner"
    description: |
      The banner that will be used as the header image for the Welcome or Main page.
    width: "40em"
  shopbanner:
    title: "Basic Shop Banner"
    description: |
      The banner that will be used as the header image for the main Shop page.
    width: "40em"
